# Generated by Django 5.0.3 on 2024-04-10 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Donor', '0002_alter_donors_email_alter_donors_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='donors',
            name='profile_photo',
            field=models.ImageField(default='dp.jpg', upload_to='Donor/'),
        ),
    ]
