# Generated by Django 5.0.3 on 2024-04-08 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Organization', '0002_verifiedorganizations'),
    ]

    operations = [
        migrations.AddField(
            model_name='unverifiedorganizations',
            name='Type',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='verifiedorganizations',
            name='Type',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.CreateModel(
            name='OrganizationStatistics',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('number_of_girls', models.IntegerField(default=0)),
                ('number_of_boys', models.IntegerField(default=0)),
                ('number_of_men', models.IntegerField(default=0)),
                ('number_of_women', models.IntegerField(default=0)),
                ('expenditure', models.IntegerField(default=0)),
                ('organization_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Organization.verifiedorganizations')),
            ],
        ),
    ]
