# Generated by Django 5.0.3 on 2024-04-08 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Organization', '0003_unverifiedorganizations_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='unverifiedorganizations',
            name='password',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='verifiedorganizations',
            name='password',
            field=models.CharField(default='', max_length=150),
        ),
    ]
