# Generated by Django 5.0.3 on 2024-04-09 09:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Organization', '0005_organizationprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='verifiedorganizations',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
