# Generated by Django 5.0.3 on 2024-04-09 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Organization', '0006_verifiedorganizations_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verifiedorganizations',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
