# Generated by Django 5.0.3 on 2024-04-09 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Organization', '0007_alter_verifiedorganizations_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationprofile',
            name='fields',
            field=models.JSONField(default=dict),
        ),
    ]
