# Generated by Django 5.0.3 on 2024-04-09 05:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Donor', '0001_initial'),
        ('Organization', '0005_organizationprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donations',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.IntegerField()),
                ('transaction_id', models.CharField(max_length=200)),
                ('date', models.DateField(auto_now_add=True)),
                ('donor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Donor.donors')),
                ('organization_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Organization.verifiedorganizations')),
            ],
        ),
    ]
