# Generated by Django 5.0.3 on 2024-04-09 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payment', '0002_donations_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donations',
            name='transaction_id',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
