# Generated by Django 5.0.3 on 2024-04-09 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payment', '0003_alter_donations_transaction_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='donations',
            name='donor_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
