# Generated by Django 5.0.3 on 2024-04-10 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payment', '0004_donations_donor_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='donations',
            name='organization_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
