# Generated by Django 5.0.3 on 2024-04-10 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manager', '0002_alter_manager_email_alter_manager_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='photo',
            field=models.ImageField(default='Admin/dp.jpg', upload_to='Admin/'),
        ),
    ]
